# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab01-deployment
  labels:
    app: lab01
spec:
  selector:
    matchLabels:
      app: lab01
  replicas: 2
  template:
    metadata:
      labels:
        app: lab01
    spec:
      containers:
      - name: lab01
        image: "rolandop/lab01:14"
        ports:
        - containerPort: 80
          name: http